buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.ratpack:ratpack-gradle:2.0.0-rc-1"
    }
}

apply plugin: "io.ratpack.ratpack-java"
apply plugin: "idea"
apply plugin: "application"

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly "org.slf4j:slf4j-simple:1.7.36"
    implementation "io.ratpack:ratpack-guice:2.0.0-rc-1"
    implementation "com.zaxxer:HikariCP:5.1.0"
    implementation "com.microsoft.sqlserver:mssql-jdbc:12.6.1.jre11"
    implementation "io.jsonwebtoken:jjwt-api:0.11.5"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:0.11.5"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:0.11.5"
    implementation "org.mindrot:jbcrypt:0.4"
    implementation "org.hibernate.validator:hibernate-validator:8.0.1.Final"
    implementation "jakarta.validation:jakarta.validation-api:3.0.2"
    implementation "org.glassfish:jakarta.el:4.0.2"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'org.example.Main'
}

test {
    useJUnitPlatform()
}