buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.ratpack:ratpack-gradle:2.0.0-rc-1"
    }
}

apply plugin: "io.ratpack.ratpack-java"
apply plugin: "idea"
apply plugin: "application"

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly "org.slf4j:slf4j-simple:1.7.36"
    implementation "io.ratpack:ratpack-guice:2.0.0-rc-1"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'org.example.Main'
}

test {
    useJUnitPlatform()
}